### ISSUE TITLE
Potentially failed deploy

### ISSUE THREAD

**Issue by sgronlund** [theo8theo8/Promille-gott#2]
It's seems like there is an issue with accessing your latest Vercel deploy, is it something you're looking at or have planned fix for?

**Comment by sgronlund** [comment]
@theo8theo8

**Comment by theo8theo8** [comment]
Hi @sgronlund and thank you for your interest in my project. 

The team and I are aware of the problem and currently working on a fix for it. I will add you to my mailing list where all further updates will be posted.

Have a great Easter,
Theo
